Create docker-compose.yml
mbentley/docker-omada-controller pull request #98
Opened 2021-04-11 22:13 UTC by whitlocktech

A proposed docker compose for your image. I used it to setup my controller with your image.

2021-04-12 10:50 UTC, mbentley requested changes
Thanks for the PR!  Typically when I have an example or a Docker Compose file (in other projects), I try to keep all of the settings to defaults for the image, which is why all of the comments.

Thanks!

2021-04-12 10:50 UTC, mbentley commented on docker-compose.yml
> +
Nit: extra space isn't needed

2021-04-12 10:50 UTC, mbentley commented on docker-compose.yml
> +     container_name: Omada
change `Omada` to `omada-controller`

2021-04-12 10:50 UTC, mbentley commented on docker-compose.yml
> +      - TZ=America/Chicago
Change to `TZ=Etc/UTC`

2021-04-12 10:50 UTC, mbentley commented on docker-compose.yml
> +#      - SSL_CERT_NAME="tls.crt"
Remove comment - it's the default certs.

2021-04-12 10:50 UTC, mbentley commented on docker-compose.yml
> +#      - SSL_KEY_NAME="tls.key"
Remove comment - it's the default certs.

2021-04-12 10:50 UTC, mbentley commented on docker-compose.yml
> +     ports:
Remove the entire ports section for `network_mode: host` ignores ports.

2021-04-12 10:50 UTC, mbentley commented on docker-compose.yml
> +     network_mode:host
Nit: space between the colon and `host`.

2021-04-12 10:50 UTC, mbentley commented on docker-compose.yml
> +     volumes:
For each of the volumes, remove the `<Insert Path here>/`

2021-04-12 10:50 UTC, mbentley commented on docker-compose.yml
> +     restart: always
Change to `unless-stopped`

2021-04-12 12:45 UTC, whitlocktech commented
I will update it even I get home this week. Port section was leftover from before I used ghost mode. But I will update it based on your comments.

2021-04-14 03:00 UTC, whitlocktech commented
@mbentley All changes have been made per request

2021-04-16 13:29 UTC, mbentley approved these changes
Thanks for the updates.  LGTM

2021-04-16 13:29 UTC, merged